apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  server: palworld-server

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: server-conf
    envs:
      - config.env