kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: server-statefulset
  namespace: palworld-server
  labels:
    deploy: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: thijsvanloef/palworld-server-docker:v0.8.0
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /palworld/
              name: palworld-server-data-volume
          ports:
            - containerPort: 27015
              protocol: UDP
            - containerPort: 8211
              protocol: UDP
          envFrom:
            - configMapRef:
                name: server-conf
            - secretRef:
                name: server-secret

      volumes:
        - name: palworld-server-data-volume
          persistentVolumeClaim:
            claimName: palworld-server-data-pvc