apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc
spec:
  template:
    spec:
      containers:
        - name: mc
          envFrom:
            - secretRef:
                name: mc-config-secret
          volumeMounts:
            - name: mc-plugins-list-file
              mountPath: /extras
            - name: mc-config-files
              mountPath: "/config"
              readOnly: true

      volumes:
        - name: mc-plugins-list-file
          configMap:
            name: mc-plugins-list
        - name: mc-config-files
          configMap:
            name: mc-config-files
