replicaCount: 1
service:
  type: ClusterIP
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: nostr.ichigo.dev
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
persistence:
  enabled: true
config:
  info:
    description: "A nostr-rs-relay on ichigo.dev"
    name: "ichigo relay"
    relay_url: wss://nostr.ichigo.dev
  authorization:
    # -- Enable NIP-42 authentication
    nip42_auth: true
  #   # -- Send DMs and gift wraps only to their authenticated recipients
  #   nip42_dms: true