apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ingress-nginx
    repoURL: https://github.com/petitstrawberry/argo-manifests.git
    targetRevision: main
  syncPolicy:
    automated: {}
