apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
spec:
  destination:
    namespace: kubescape
    server: 'https://kubernetes.default.svc' # change to your server
  sources:
    - ref: values
      repoURL: https://github.com/petitstrawberry/argo-secrets.git
      targetRevision: main
    - path: charts/kubescape-operator
      repoURL: 'https://github.com/kubescape/helm-charts'
      targetRevision: kubescape-operator-1.18.1
      helm:
        valueFiles:
          - '$values/kubescape/values.yml'
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: core
      kind: ConfigMap
      name: ks-cloud-config
      namespace: kubescape
      jsonPointers:
        - /data
        - /metadata