apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-static-provisioner
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/sig-storage-local-static-provisioner
      targetRevision: 2.8.0
      chart: local-static-provisioner
      helm:
        valuesObject:
          classes:
            - name: local-storage
              hostDir: /mnt/fast-disks
              volumeMode: Filesystem
              fsType: ext4
              storageClass: true
  destination:
    server: https://kubernetes.default.svc
    namespace: local-static-provisioner
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true