apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.11
    chart: metallb

  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
