apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey
  namespace: argocd
spec:
  destination:
    namespace: misskey
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: misskey
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main

    - path: misskey
      repoURL: https://github.com/petitstrawberry/argo-secrets.git
      targetRevision: main

    - repoURL: https://meilisearch.github.io/meilisearch-kubernetes
      targetRevision: 0.4.0
      chart: meilisearch
      helm:
        valuesObject:
          persistence:
            enabled: true
            storageClass: nfs-client
          environment:
            MEILI_ENV: production
          envFrom:
            - secretRef:
                name: meilisearch-secrets
  syncPolicy:
    automated: {}
