apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: misskey
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main

    - path: misskey
      repoURL: https://github.com/petitstrawberry/argo-secrets.git
      targetRevision: main

    - repoURL: https://meilisearch.github.io/meilisearch-kubernetes
      targetRevision: 0.3.0
      chart: meilisearch
      helm:
        parameters:
          - name: "persistence.enabled"
            value: "true"
  syncPolicy:
    automated: {}
