apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: misskey
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main

    - path: misskey
      repoURL: https://github.com/petitstrawberry/argo-secrets.git
      targetRevision: main
  syncPolicy:
    automated: {}
