apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: nfs-provisioner
    repoURL: https://github.com/petitstrawberry/argo-manifests.git
    targetRevision: main
  syncPolicy:
    automated: {}
