apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
spec:
  destination:
    namespace: postgres-operator
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      targetRevision: 1.10.1
      chart: postgres-operator
    - repoURL: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
      targetRevision: 1.10.0
      chart: postgres-operator-ui

  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true

