apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-private
  namespace: argocd
spec:
  project: default
  sources:
    - path: vclusters/private
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main
    - chart: vcluster
      repoURL: https://charts.loft.sh
      targetRevision: 0.21.2
      helm:
        releaseName: vcluster-private
        valuesObject:
          exportKubeConfig:
            server: https://private.k8s.ichigo.dev
          controlPlane:
            backingStore:
              etcd:
                deploy:
                  enabled: true
            distro:
              k3s:
                enabled: true
            statefulSet:
              scheduling:
                podManagementPolicy: OrderedReady
            proxy:
              extraSANs:
              - private.k8s.ichigo.dev
          sync:
            toHost:
              persistentVolumes:
                enabled: true
              storageClasses:
                enabled: true
          policies:
            podSecurityStandard: baseline
            resourceQuota:
              enabled: true
            limitRange:
              enabled: true
            networkPolicy:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
