apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-private
  namespace: argocd
spec:
  project: default
  sources:
    - path: vclusters/private
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main
    - chart: vcluster
      repoURL: https://charts.loft.sh
      targetRevision: 0.22.3
      helm:
        releaseName: vcluster-private
        valuesObject:
          exportKubeConfig:
            server: https://private.k8s.ichigo.dev
            context: vcluster-private
          controlPlane:
            distro:
              k8s:
                enabled: true
            statefulSet:
              highAvailability:
                replicas: 3
              persistence:
                volumeClaimTemplates:
                  - metadata:
                      name: data
                    spec:
                      accessModes: [ "ReadWriteOnce" ]
                      storageClassName: local-storage
                      resources:
                        requests:
                          storage: 4Gi
            backingStore:
              etcd:
                deploy:
                  enabled: true
                  statefulSet:
                    highAvailability:
                      replicas: 3
                    persistence:
                      volumeClaimTemplates:
                        - metadata:
                            name: data
                          spec:
                            accessModes: [ "ReadWriteOnce" ]
                            storageClassName: local-storage
                            resources:
                              requests:
                                storage: 4Gi
            proxy:
              extraSANs:
              - private.k8s.ichigo.dev
          sync:
            toHost:
              persistentVolumes:
                enabled: true
              storageClasses:
                enabled: true
              ingresses:
                  enabled: true
          policies:
            podSecurityStandard: baseline
            resourceQuota:
              enabled: true
              quota:
                pods: "40"
            limitRange:
              enabled: true
            networkPolicy:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-private
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
