# postgresql cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: misskey-postgres-cluster
  namespace: misskey
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  minSyncReplicas: 1
  maxSyncReplicas: 2
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      storageClassName: nfs-client
      resources:
        requests:
          storage: 70Gi

  postgresql:
    parameters:
      max_connections: "128"
      shared_buffers: "2GB"
      effective_cache_size: "6GB"
      maintenance_work_mem: "512MB"
      checkpoint_completion_target: "0.7"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "300"
      work_mem: "8MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"
      max_parallel_maintenance_workers: "2"

  bootstrap:
    initdb:
      database: misskey
      owner: misskey
      # secretsは別のプライベートリポジトリに置いてる
      secret:
        name: postgres-local-user-secret

  # backup
  backup:
    barmanObjectStore:
      destinationPath: "s3://misskey-db-backup/"
      endpointURL: "https://axknve1vrtoq.compat.objectstorage.ap-osaka-1.oraclecloud.com"
      # Secretsは別のプライベートリポジトリに置いてる
      s3Credentials:
        accessKeyId:
          name: creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
    retentionPolicy: "7d" # 7日で削除

  monitoring:
    enablePodMonitor: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: backup-misskey
  namespace: misskey
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: misskey-postgres-cluster
