apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: overleaf-data
  name: overleaf-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi