command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: admin
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
proxy:
  enabled: true
  mode: xforwarded
  http:
    enabled: true

ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  rules:
    - host: 'auth.ichigo.dev'
      paths:
        - path: /
          pathType: Prefix

http:
  relativePath: "/"
  internalPort: http-internal
  internalScheme: HTTP

autoscaling:
  enabled: true