command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
proxy:
  enabled: true
  mode: xforwarded
  http:
    enabled: true

ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: http
  rules:
    - host: 'auth.ichigo.dev'
      paths:
        - path: /
          pathType: Prefix

http:
  relativePath: "/"
  internalPort: http-internal
  internalScheme: HTTP

autoscaling:
  enabled: true
