extraEnv: |
  - name: KC_PROXY_HEADERS
    value: "xforwarded"
  - name: KC_PROXY_PROTOCOL_ENABLED
    value: "true"
  - name: KC_HOSTNAME
    value: "auth.ichigo.dev"
ingress:
  enabled: true
  ingressClassName: "nginx"
  servicePort: https
  rules:
    - host: 'auth.ichigo.dev'
      paths:
        - path: /
          pathType: Prefix