keycloak:
  ingress:
    enabled: true
    path: /
    hosts:
      - auth.ichigo.dev
    tls:
      hosts:
        - auth.ichigo.dev
  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"