apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-ingress-deny-engress-policy
  namespace: vcluster-private
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  - Ingress
  egress:
    - to:
      - podSelector: {}
  ingress:
    - {}
