apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal-policy
  namespace: vcluster-private
spec:
  podSelector: 
    matchLabels: {}
  policyTypes:
  - Egress
  egress:
    - to:
      - podSelector: {}

