apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-ingress-deny-engress-policy
  namespace: vcluster-private
spec:
  podSelector: {}
  policyTypes:
  - Egress
  - Ingress
  egress: []
  ingress:
  - {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-vcluster-engress-policy
  namespace: vcluster-private
spec:
  podSelector:
    matchLabels:
      app: vcluster
  policyTypes:
  - Egress
  egress:
  - {}

