commonLabels:
  server: proxy

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: proxy
    envs:
      - proxy.env
  - name: proxy-config
    files:
      - config/velocity.toml