apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
    - name: minecraft
      port: 25575
      targetPort: 25565
    - name: minecraft-be
      protocol: UDP
      port: 19132
      targetPort: 19132
  type: LoadBalancer
  LoadBalancerIP: 192.168.10.103