apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  serviceName: proxy
  selector:
    matchLabels:
      server: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - image: itzg/bungeecord:java17
          name: proxy
          envFrom:
            - configMapRef:
                name: proxy
          volumeMounts:
            - name: data
              mountPath: /server
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                name: config
              - secret:
                name: config-secret

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi