apiVersion: v1
data:
  paper-global.yml : |
    # This is the global configuration file for Paper.
    # As you can see, there's a lot to configure. Some options may impact gameplay, so use
    # with caution, and make sure you know what each option does before configuring.
    #
    # If you need help with the configuration or have any questions related to Paper,
    # join us in our Discord or check the docs page.
    #
    # The world configuration options have been moved inside
    # their respective world folder. The files are named paper-world.yml
    #
    # Docs: https://docs.papermc.io/
    # Discord: https://discord.gg/papermc
    # Website: https://papermc.io/

    _version: 29
    block-updates:
      disable-chorus-plant-updates: false
      disable-mushroom-block-updates: false
      disable-noteblock-updates: false
      disable-tripwire-updates: false
    chunk-loading-advanced:
      auto-config-send-distance: true
      player-max-concurrent-chunk-generates: 0
      player-max-concurrent-chunk-loads: 0
    chunk-loading-basic:
      player-max-chunk-generate-rate: -1.0
      player-max-chunk-load-rate: 100.0
      player-max-chunk-send-rate: 75.0
    chunk-system:
      gen-parallelism: default
      io-threads: -1
      worker-threads: -1
    collisions:
      enable-player-collisions: true
      send-full-pos-for-hard-colliding-entities: true
    commands:
      fix-target-selector-tag-completion: true
      suggest-player-names-when-null-tab-completions: true
      time-command-affects-all-worlds: false
    console:
      enable-brigadier-completions: true
      enable-brigadier-highlighting: true
      has-all-permissions: false
    item-validation:
      book:
        author: 8192
        page: 16384
        title: 8192
      book-size:
        page-max: 2560
        total-multiplier: 0.98
      display-name: 8192
      lore-line: 8192
      resolve-selectors-in-books: false
    logging:
      deobfuscate-stacktraces: true
    messages:
      kick:
        authentication-servers-down: <lang:multiplayer.disconnect.authservers_down>
        connection-throttle: Connection throttled! Please wait before reconnecting.
        flying-player: <lang:multiplayer.disconnect.flying>
        flying-vehicle: <lang:multiplayer.disconnect.flying>
      no-permission: <red>I'm sorry, but you do not have permission to perform this command.
        Please contact the server administrators if you believe that this is in error.
      use-display-name-in-quit-message: false
    misc:
      chat-threads:
        chat-executor-core-size: -1
        chat-executor-max-size: -1
      compression-level: default
      fix-entity-position-desync: true
      load-permissions-yml-before-plugins: true
      max-joins-per-tick: 5
      region-file-cache-size: 256
      strict-advancement-dimension-check: false
      use-alternative-luck-formula: false
      use-dimension-type-for-custom-spawners: false
    packet-limiter:
      all-packets:
        action: KICK
        interval: 7.0
        max-packet-rate: 500.0
      kick-message: <red><lang:disconnect.exceeded_packet_rate>
      overrides:
        ServerboundPlaceRecipePacket:
          action: DROP
          interval: 4.0
          max-packet-rate: 5.0
    player-auto-save:
      max-per-tick: -1
      rate: -1
    proxies:
      bungee-cord:
        online-mode: true
      proxy-protocol: false
      velocity:
        enabled: false
        online-mode: false
        secret: ''
    scoreboards:
      save-empty-scoreboard-teams: false
      track-plugin-scoreboards: false
    spam-limiter:
      incoming-packet-threshold: 300
      recipe-spam-increment: 1
      recipe-spam-limit: 20
      tab-spam-increment: 1
      tab-spam-limit: 500
    timings:
      enabled: true
      hidden-config-entries:
      - database
      - proxies.velocity.secret
      history-interval: 300
      history-length: 3600
      server-name: Unknown Server
      server-name-privacy: false
      url: https://timings.aikar.co/
      verbose: true
    unsupported-settings:
      allow-grindstone-overstacking: false
      allow-headless-pistons: false
      allow-permanent-block-break-exploits: false
      allow-piston-duplication: false
      compression-format: ZLIB
      perform-username-validation: true
    watchdog:
      early-warning-delay: 10000
      early-warning-every: 5000
  paper-world-defaults.yml : |
    # This is the world defaults configuration file for Paper.
    # As you can see, there's a lot to configure. Some options may impact gameplay, so use
    # with caution, and make sure you know what each option does before configuring.
    #
    # If you need help with the configuration or have any questions related to Paper,
    # join us in our Discord or check the docs page.
    #
    # Configuration options here apply to all worlds, unless you specify overrides inside
    # the world-specific config file inside each world folder.
    #
    # Docs: https://docs.papermc.io/
    # Discord: https://discord.gg/papermc
    # Website: https://papermc.io/

    _version: 30
    anticheat:
      anti-xray:
        enabled: false
        engine-mode: 1
        hidden-blocks:
        - copper_ore
        - deepslate_copper_ore
        - raw_copper_block
        - gold_ore
        - deepslate_gold_ore
        - iron_ore
        - deepslate_iron_ore
        - raw_iron_block
        - coal_ore
        - deepslate_coal_ore
        - lapis_ore
        - deepslate_lapis_ore
        - mossy_cobblestone
        - obsidian
        - chest
        - diamond_ore
        - deepslate_diamond_ore
        - redstone_ore
        - deepslate_redstone_ore
        - clay
        - emerald_ore
        - deepslate_emerald_ore
        - ender_chest
        lava-obscures: false
        max-block-height: 64
        replacement-blocks:
        - stone
        - oak_planks
        - deepslate
        update-radius: 2
        use-permission: false
      obfuscation:
        items:
          hide-durability: false
          hide-itemmeta: false
          hide-itemmeta-with-visual-effects: false
    chunks:
      auto-save-interval: default
      delay-chunk-unloads-by: 10s
      entity-per-chunk-save-limit:
        arrow: -1
        ender_pearl: -1
        experience_orb: -1
        fireball: -1
        small_fireball: -1
        snowball: -1
      fixed-chunk-inhabited-time: -1
      flush-regions-on-save: false
      max-auto-save-chunks-per-tick: 24
      prevent-moving-into-unloaded-chunks: false
    collisions:
      allow-player-cramming-damage: false
      allow-vehicle-collisions: true
      fix-climbing-bypassing-cramming-rule: false
      max-entity-collisions: 8
      only-players-collide: false
    entities:
      armor-stands:
        do-collision-entity-lookups: true
        tick: true
      behavior:
        allow-spider-world-border-climbing: true
        baby-zombie-movement-modifier: 0.5
        disable-chest-cat-detection: false
        disable-creeper-lingering-effect: false
        disable-player-crits: false
        door-breaking-difficulty:
          husk:
          - HARD
          vindicator:
          - NORMAL
          - HARD
          zombie:
          - HARD
          zombie_villager:
          - HARD
          zombified_piglin:
          - HARD
        ender-dragons-death-always-places-dragon-egg: false
        experience-merge-max-value: -1
        mobs-can-always-pick-up-loot:
          skeletons: false
          zombies: false
        nerf-pigmen-from-nether-portals: false
        parrots-are-unaffected-by-player-movement: false
        phantoms-do-not-spawn-on-creative-players: true
        phantoms-only-attack-insomniacs: true
        phantoms-spawn-attempt-max-seconds: 119
        phantoms-spawn-attempt-min-seconds: 60
        piglins-guard-chests: true
        pillager-patrols:
          disable: false
          spawn-chance: 0.2
          spawn-delay:
            per-player: false
            ticks: 12000
          start:
            day: 5
            per-player: false
        player-insomnia-start-ticks: 72000
        should-remove-dragon: false
        spawner-nerfed-mobs-should-jump: false
        zombie-villager-infection-chance: default
        zombies-target-turtle-eggs: true
      entities-target-with-follow-range: false
      markers:
        tick: true
      mob-effects:
        immune-to-wither-effect:
          wither: true
          wither-skeleton: true
        spiders-immune-to-poison-effect: true
        undead-immune-to-certain-effects: true
      sniffer:
        boosted-hatch-time: default
        hatch-time: default
      spawning:
        all-chunks-are-slime-chunks: false
        alt-item-despawn-rate:
          enabled: false
          items:
            cobblestone: 300
        count-all-mobs-for-spawning: false
        creative-arrow-despawn-rate: default
        despawn-ranges:
          ambient:
            hard: 128
            soft: 32
          axolotls:
            hard: 128
            soft: 32
          creature:
            hard: 128
            soft: 32
          misc:
            hard: 128
            soft: 32
          monster:
            hard: 128
            soft: 32
          underground_water_creature:
            hard: 128
            soft: 32
          water_ambient:
            hard: 64
            soft: 32
          water_creature:
            hard: 128
            soft: 32
        disable-mob-spawner-spawn-egg-transformation: false
        duplicate-uuid:
          mode: SAFE_REGEN
          safe-regen-delete-range: 32
        filter-bad-tile-entity-nbt-from-falling-blocks: true
        filtered-entity-tag-nbt-paths:
        - Pos
        - Motion
        - SleepingX
        - SleepingY
        - SleepingZ
        iron-golems-can-spawn-in-air: false
        monster-spawn-max-light-level: default
        non-player-arrow-despawn-rate: default
        per-player-mob-spawns: true
        scan-for-legacy-ender-dragon: true
        skeleton-horse-thunder-spawn-chance: default
        slime-spawn-height:
          slime-chunk:
            maximum: 40.0
          surface-biome:
            maximum: 70.0
            minimum: 50.0
        spawn-limits:
          ambient: -1
          axolotls: -1
          creature: -1
          monster: -1
          underground_water_creature: -1
          water_ambient: -1
          water_creature: -1
        wandering-trader:
          spawn-chance-failure-increment: 25
          spawn-chance-max: 75
          spawn-chance-min: 25
          spawn-day-length: 24000
          spawn-minute-length: 1200
        wateranimal-spawn-height:
          maximum: default
          minimum: default
      tracking-range-y:
        animal: default
        display: default
        enabled: false
        misc: default
        monster: default
        other: default
        player: default
    environment:
      disable-explosion-knockback: false
      disable-ice-and-snow: false
      disable-teleportation-suffocation-check: false
      disable-thunder: false
      fire-tick-delay: 30
      frosted-ice:
        delay:
          max: 40
          min: 20
        enabled: true
      generate-flat-bedrock: false
      nether-ceiling-void-damage-height: disabled
      optimize-explosions: false
      portal-create-radius: 16
      portal-search-radius: 128
      portal-search-vanilla-dimension-scaling: true
      treasure-maps:
        enabled: true
        find-already-discovered:
          loot-tables: default
          villager-trade: false
      water-over-lava-flow-speed: 5
    feature-seeds:
      generate-random-seeds-for-all: false
    fishing-time-range:
      maximum: 600
      minimum: 100
    fixes:
      disable-unloaded-chunk-enderpearl-exploit: true
      falling-block-height-nerf: disabled
      fix-items-merging-through-walls: false
      prevent-tnt-from-moving-in-water: false
      split-overstacked-loot: true
      tnt-entity-height-nerf: disabled
    hopper:
      cooldown-when-full: true
      disable-move-event: false
      ignore-occluding-blocks: false
    lootables:
      auto-replenish: false
      max-refills: -1
      refresh-max: 2d
      refresh-min: 12h
      reset-seed-on-fill: true
      restrict-player-reloot: true
      restrict-player-reloot-time: disabled
    maps:
      item-frame-cursor-limit: 128
      item-frame-cursor-update-interval: 10
    max-growth-height:
      bamboo:
        max: 16
        min: 11
      cactus: 3
      reeds: 3
    misc:
      disable-end-credits: false
      disable-relative-projectile-velocity: false
      disable-sprint-interruption-on-attack: false
      light-queue-size: 20
      max-leash-distance: 10.0
      redstone-implementation: VANILLA
      shield-blocking-delay: 5
      show-sign-click-command-failure-msgs-to-player: false
      update-pathfinding-on-block-update: true
    scoreboards:
      allow-non-player-entities-on-scoreboards: true
      use-vanilla-world-scoreboard-name-coloring: false
    spawn:
      allow-using-signs-inside-spawn-protection: false
      keep-spawn-loaded: true
      keep-spawn-loaded-range: 10
    tick-rates:
      behavior:
        villager:
          validatenearbypoi: -1
      container-update: 1
      dry-farmland: 1
      grass-spread: 1
      mob-spawner: 1
      sensor:
        villager:
          secondarypoisensor: 40
      wet-farmland: 1
    unsupported-settings:
      fix-invulnerable-end-crystal-exploit: true


kind: ConfigMap
metadata:
  name: mc-server-configs
  namespace: omochimc
