nameSuffix: "-paper"
commonLabels:
  server: paper
bases:
  - https://github.com/itzg/docker-minecraft-server.git/kustomize/base?ref=2023.12.1
resources:
  - plugins.yml
patchesStrategicMerge:
  - statefulset.yml
  - service.yml
configMapGenerator:
  - name: mc
    envs:
      - mc.env