apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    targetRevision: 0.11.0
    chart: arc
  destination:
    server:  https://private.k8s.ichigo.dev
    namespace: arc-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true