apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://private.k8s.ichigo.dev
  project: default
  sources:
    - path: vclusters/private/keycloak
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main
    - path: vclusters/private/keycloak
      repoURL: https://github.com/petitstrawberry/argo-secrets.git
      targetRevision: main
    - repoURL: https://codecentric.github.io/helm-charts
      targetRevision: 18.6.0
      chart: keycloak
      helm:
        valueFiles:
          - values.yml
          - values-secret.yml
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
