apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak
    server: https://private.k8s.ichigo.dev
  project: default
  sources:
    - path: vclusters/private/keycloak
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main
      ref: main
    - path: vclusters/private/keycloak
      repoURL: https://github.com/petitstrawberry/argo-secrets.git
      targetRevision: main
      ref: secret
    - repoURL: https://codecentric.github.io/helm-charts
      targetRevision: 5.0.0
      chart: keycloakx
      helm:
        valueFiles:
          - $main/vclusters/private/keycloak/values.yml
          - $secret/vclusters/private/keycloak/values-secret.yml
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
