apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://192.168.10.80
  project: default
  sources:
    - path: vclusters/private/nginx
      repoURL: https://github.com/petitstrawberry/argo-manifests.git
      targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true