apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overleaf
  namespace: argocd
spec:
  destination:
    namespace: overleaf
    server: https://private.k8s.ichigo.dev
  project: default
  sources:
    - repoURL: https://k8s-at-home.com/charts/
      targetRevision: 3.1.2
      chart: overleaf
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
